# Generated by Django 4.1.6 on 2023-02-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dept_name',
            field=models.CharField(choices=[('stores', 'Stores'), ('kitchen', 'Kitchen'), ('h2', 'Holistic Health'), ('aura', 'Aura'), ('maintenance', 'Maintenance'), ('altar', 'Altar'), ('ankur', 'ankur'), ('he', 'Hostel Essentials'), ('multimedia', 'Multimedia')], max_length=15),
        ),
    ]
