# Generated by Django 4.1.6 on 2023-02-17 05:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_dept_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('new_user', django.db.models.manager.Manager()),
            ],
        ),
    ]
