# Generated by Django 4.1.6 on 2023-03-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_year',
            field=models.CharField(blank=True, choices=[('I UG BBA', 'I UG BBA'), ('I UG BSc', 'I UG BSc'), ('II UG BBA', 'II UG BBA'), ('II UG BSc', 'II UG BSc'), ('III UG BBA', 'III UG BBA'), ('III UG BSc', 'III UG BSc'), ('I PG MSc', 'I PG MSc'), ('II PG MSc', 'II PG MSc')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept_name',
            field=models.CharField(choices=[('Stores', 'Stores'), ('Kitchen', 'Kitchen'), ('Holistic Health', 'Holistic Health'), ('Aura', 'Aura'), ('Maintenance', 'Maintenance'), ('Altar', 'Altar'), ('Ankur', 'Ankur'), ('Hostel Essentials', 'Hostel Essentials'), ('Multimedia', 'Multimedia')], max_length=20),
        ),
    ]
