# Generated by Django 4.1.6 on 2023-04-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_student_year_alter_user_dept_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_hod',
            new_name='can_accept_tickets',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='can_modify_frts',
        ),
        migrations.AlterField(
            model_name='user',
            name='dept_name',
            field=models.CharField(choices=[('Stores', 'Stores'), ('Kitchen', 'Kitchen'), ('Holistic Health', 'Holistic Health'), ('Aura', 'Aura'), ('Maintenance', 'Maintenance'), ('Altar', 'Altar'), ('Ankur', 'Ankur'), ('Hostel Essentials', 'Hostel Essentials'), ('Multimedia', 'Multimedia'), ('Music', 'Music')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
