# Generated by Django 4.1.6 on 2023-04-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dept_name',
            field=models.CharField(choices=[('Stores', 'Stores'), ('Kitchen', 'Kitchen'), ('Holistic Health', 'Holistic Health'), ('Aura', 'Aura'), ('Maintenance', 'Maintenance'), ('Altar', 'Altar'), ('Ankur', 'Ankur'), ('Hostel Essentials', 'Hostel Essentials'), ('Multimedia', 'Multimedia'), ('Music', 'Music'), ('Telephone', 'Telephone')], max_length=20),
        ),
    ]
