# Generated by Django 4.1.6 on 2023-04-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements_model',
            name='Title',
            field=models.CharField(max_length=30),
        ),
    ]
