# Generated by Django 4.1.5 on 2023-01-26 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_model',
            fields=[
                ('tkt_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('desc', models.TextField(max_length=300)),
                ('dept_name', models.CharField(max_length=20)),
                ('suggestions', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Queries_corner',
                'db_table': 'tickets',
            },
        ),
    ]
