# Generated by Django 4.1.5 on 2023-01-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='dept_name',
            field=models.CharField(choices=[('stores', 'Stores'), ('kitchen', 'Kitchen'), ('h2', 'Holistic Health'), ('aura', 'Aura'), ('maintenance', 'Maintenance'), ('altar', 'Altar'), ('ankur', 'ankur'), ('he', 'Hostel Essentials')], max_length=20),
        ),
    ]
