# Generated by Django 4.1.5 on 2023-01-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0003_alter_ticket_model_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_model',
            name='accepted_by',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
