# Generated by Django 4.1.6 on 2023-02-07 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0004_ticket_model_accepted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='dept_name',
            field=models.CharField(choices=[('stores', 'Stores'), ('kitchen', 'Kitchen'), ('h2', 'Holistic Health'), ('aura', 'Aura'), ('maintenance', 'Maintenance'), ('altar', 'Altar'), ('ankur', 'ankur'), ('he', 'Hostel Essentials'), ('multimedia', 'Multimedia')], max_length=20),
        ),
        migrations.CreateModel(
            name='comments_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('for_ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raise_tktapp.ticket_model')),
            ],
            options={
                'db_table': 'Solutions_corner',
            },
        ),
    ]
