# Generated by Django 4.1.6 on 2023-02-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0005_alter_ticket_model_dept_name_comments_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='accepted_by',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
