# Generated by Django 4.1.6 on 2023-02-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0010_alter_ticket_model_accepted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='dept_name',
            field=models.CharField(choices=[('stores', 'Stores'), ('kitchen', 'Kitchen'), ('h2', 'Holistic Health'), ('aura', 'Aura'), ('maintenance', 'Maintenance'), ('altar', 'Altar'), ('ankur', 'ankur'), ('he', 'Hostel Essentials'), ('multimedia', 'Multimedia'), ('telephone', 'Telephone')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket_model',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
