# Generated by Django 4.1.6 on 2023-02-17 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raise_tktapp', '0011_alter_ticket_model_dept_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_model',
            name='commented_by',
            field=models.ForeignKey(blank=True, default='none', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
