# Generated by Django 4.1.6 on 2023-03-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0013_frqt_tkt_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frqt_tkt_model',
            name='image',
            field=models.ImageField(upload_to='frqt_tkt_imgs/'),
        ),
    ]
