# Generated by Django 4.1.6 on 2023-03-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0014_alter_frqt_tkt_model_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_model',
            old_name='is_accepted',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='ticket_model',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='ticket_model',
            name='dept_name',
            field=models.CharField(max_length=20),
        ),
    ]
