# Generated by Django 4.1.6 on 2023-03-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0015_rename_is_accepted_ticket_model_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='desc',
            field=models.JSONField(),
        ),
    ]
