# Generated by Django 4.1.6 on 2023-03-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0016_alter_ticket_model_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='dept_name',
            field=models.CharField(max_length=15),
        ),
    ]
