# Generated by Django 4.1.6 on 2023-03-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0018_rename_accepted_by_ticket_model_accepted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcements_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=10)),
                ('Announcement', models.TextField()),
                ('Created_At', models.TimeField(auto_now_add=True)),
                ('Validity', models.DateTimeField()),
            ],
            options={
                'db_table': 'Announcments',
            },
        ),
    ]
