# Generated by Django 4.1.6 on 2023-03-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0020_announcements_model_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_model',
            name='Suggestions',
        ),
        migrations.AddField(
            model_name='ticket_model',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket_model',
            name='Created_At',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket_model',
            name='Status',
            field=models.CharField(max_length=10),
        ),
    ]
