# Generated by Django 4.1.6 on 2023-03-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0021_remove_ticket_model_suggestions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='Status',
            field=models.CharField(max_length=20),
        ),
    ]
