# Generated by Django 4.1.6 on 2023-03-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0022_alter_ticket_model_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='Status',
            field=models.CharField(default='To Be Accpeted', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket_model',
            name='Ticket_ID',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
