# Generated by Django 4.1.6 on 2023-03-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0023_alter_ticket_model_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='Ticket_ID',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
