# Generated by Django 4.1.6 on 2023-03-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0024_alter_ticket_model_ticket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_model',
            old_name='commented_by',
            new_name='commented_By',
        ),
        migrations.AlterField(
            model_name='ticket_model',
            name='Ticket_ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
