# Generated by Django 4.1.6 on 2023-03-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0025_rename_commented_by_comments_model_commented_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='Accepted_By',
            field=models.CharField(default='To Be Accpeted', max_length=6, null=True),
        ),
    ]
