# Generated by Django 4.1.6 on 2023-03-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0026_alter_ticket_model_accepted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frqt_tkt_model',
            name='image',
            field=models.ImageField(upload_to='media/frqt_tkt_imgs/'),
        ),
    ]
