# Generated by Django 4.1.6 on 2023-03-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0027_alter_frqt_tkt_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='Accepted_By',
            field=models.CharField(default='To Be Accpeted', max_length=10, null=True),
        ),
    ]
