# Generated by Django 4.1.6 on 2023-03-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0028_alter_ticket_model_accepted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_model',
            name='Accepted_By',
            field=models.CharField(default='To Be Accpeted', max_length=20, null=True),
        ),
    ]
