# Generated by Django 4.1.6 on 2023-03-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0030_alter_ticket_model_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frqt_tkt_model',
            name='image',
            field=models.ImageField(upload_to='frqt_tkt_imgs/'),
        ),
    ]
