# Generated by Django 4.1.6 on 2023-04-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0033_alter_ticket_model_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frqt_tkt_model',
            name='frqt_tkt_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket_model',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
