# Generated by Django 4.1.6 on 2023-04-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0034_alter_frqt_tkt_model_frqt_tkt_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket_model',
            options={'ordering': ['Status'], 'verbose_name_plural': 'Queries_corner'},
        ),
        migrations.AddField(
            model_name='ticket_model',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
