# Generated by Django 4.1.6 on 2023-04-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0035_alter_ticket_model_options_ticket_model_is_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket_model',
            options={'verbose_name_plural': 'Queries_corner'},
        ),
    ]
