# Generated by Django 4.1.6 on 2023-04-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0038_ticket_model_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_model',
            old_name='image',
            new_name='file',
        ),
    ]
