# Generated by Django 4.1.6 on 2023-04-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0039_rename_image_ticket_model_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_model',
            name='file',
        ),
    ]
