# Generated by Django 4.1.6 on 2023-04-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raise_tktapp', '0040_remove_ticket_model_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='announcements_model',
        ),
    ]
